# Generated by Django 5.1.1 on 2025-03-08 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i18nilize', '0002_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroserviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='i18nilize.token')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_permissions', to='i18nilize.microservicetoken')),
                ('project_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i18nilize.token')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project_token',), name='unique_project_token'), models.UniqueConstraint(fields=('editor_token',), name='unique_editor_token')],
            },
        ),
    ]
